org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.0
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.21.1
mod_id=uncraftablenomore
mod_name=Uncraftable No More
mod_license=MIT
mod_version=1.0.7
mod_group_id=net.withrage.uncraftablenomore
mod_authors=JustErikSK, With Rage Studios
mod_description=Want to craft items that were not originally craftable? This mod does just that!