modLoader="javafml"
loaderVersion="[66,)"
license="MIT"
[[mods]]
modId="uncraftablenomore"
version="1.0.7"
displayName="Uncraftable No More"
authors="JustErikSK, With Rage Studios"
description='''Want to craft items that were not originally craftable? This mod does just that!'''
[[dependencies.uncraftablenomore]]
    modId="forge"
    mandatory=true
    versionRange="[66,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.uncraftablenomore]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.3,26.4,)"
    ordering="NONE"
    side="BOTH"
